[options]
name = CheatDevice Remastered
type = prx
version = 1
filename = cheatdevice_remastered.prx
memory = 64

[games]

# LCS | US
ULUS10041 = true

# LCS | EU (Germany)
ULES00182 = true

# LCS | EU
ULES00151 = true

# VCS | US
ULUS10160 = true

# VCS | EU
ULES00502 = true

# VCS | EU (Germany)
ULES00503 = true

# Sindacco Chronicles
ULUS01826 = true

# Seen in Liberty City
ULUS11826 = true

# LCS | Prototype build
# https://umdatabase.net/view.php?id=170152B1
ULUX80146 = true

# VCS | "Prototype" build
# https://umdatabase.net/view.php?id=5CCF99EC
ULET00417 = true